# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('operation_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_body', models.CharField(max_length=255, verbose_name='\u6d88\u606f')),
                ('namespace', models.CharField(max_length=255, verbose_name='\u6d88\u606f\u7684namespace')),
                ('message_type', models.CharField(max_length=255, verbose_name='\u6d88\u606f\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
            bases=(models.Model, utils.mixins.HasPublicID),
        ),
    ]
