# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Message', '0001_initial'),
        ('Status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Status.Comment'),
        ),
        migrations.AddField(
            model_name='message',
            name='related_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Status.Status'),
        ),
    ]
