# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Message', '0002_auto_20160919_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u4ea7\u751f\u6d88\u606f\u7684\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='message',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u6d88\u606f\u53d1\u9001\u7684\u76ee\u6807'),
        ),
    ]
