# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(default='', max_length=255, verbose_name='\u8bbe\u5907\u7684token'),
            preserve_default=False,
        ),
    ]
