# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='\u6635\u79f0'),
            preserve_default=False,
        ),
    ]
