# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 14:37
from __future__ import unicode_literals

import Status.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Status.models.status_image, verbose_name='\u8bc4\u8bba\u56fe\u7247')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
            bases=(models.Model, utils.mixins.HasPublicID),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to=Status.models.status_image, verbose_name='\u52a8\u6001\u5c01\u9762\u56fe')),
                ('voice', models.FileField(upload_to=Status.models.status_voice, verbose_name='\u52a8\u6001\u58f0\u97f3')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='\u52a8\u6001\u5730\u70b9')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loc_des', models.CharField(db_index=True, max_length=255, verbose_name='\u5730\u70b9\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u52a8\u6001',
                'verbose_name_plural': '\u52a8\u6001',
            },
            bases=(models.Model, utils.mixins.HasPublicID),
        ),
    ]
