# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Status', '0002_auto_20160919_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u88ab\u5220\u9664'),
        ),
        migrations.AddField(
            model_name='status',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='\u52a8\u6001\u662f\u5426\u88ab\u5220\u9664'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Status.Status', verbose_name='\u52a8\u6001'),
        ),
    ]
